Fj 2024 lesson 5
Dimes01/T-Homework-Kotlin pull request #2
Opened 2024-09-25 20:31 UTC by Dimes01

2024-09-29 19:50 UTC, SHvatov reviewed
@Dimes01 код на Котлине я посмотрю, но давай следующие ДЗ писать на Java. К сожалению (или к счастью) таковы требования.

2024-09-29 20:02 UTC, SHvatov requested changes
@Dimes01 оставил комментарии, посмотри их, пожалуйста.

2024-09-29 20:02 UTC, SHvatov commented on homework5/build.gradle.kts
> +//	implementation(project(":starter"))
Закомментарованный код стоит сразу в топку отправлять)

2024-09-29 20:02 UTC, SHvatov commented on homework5/build.gradle.kts
> +	implementation("org.springframework.boot:spring-boot-starter-web")
А оно без all-open работает?

https://kotlinlang.org/docs/all-open-plugin.html

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/Homework5Application.kt
> +	runApplication<Homework5Application>(*args)
Как-будто таб чуть больше, чем надо)

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/aspects/LogExecutionTimeAspect.kt
> +    private val logger = LoggerFactory.getLogger(LogExecutionTimeAspect::class.java)
Я логгеры держу в companion object'е

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/aspects/LogExecutionTimeAspect.kt
> +    private val logger = LoggerFactory.getLogger(LogExecutionTimeAspect::class.java)
Но там и так, и так будет синглтон, просто разделение обязанностей так сказать - утильный логгер, и поля класса, которые реально нужны для его работы.

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/aspects/LogExecutionTimeAspect.kt
> +        val start = System.currentTimeMillis()
Раз уж мы на модном и напичканным сахаром котлине пишем, то давай так - https://kotlinlang.org/docs/time-measurement.html#measure-code-execution-time

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/models/Location.kt
> + * `MissingKotlinParameterException: Instantiation of [simple type, class ...Location] value failed for JSON property
Сделать его nullable и добавить дефолтное значение null, либо пометить как lateinit, унести в тело и там написать кастомный десериализатор.

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/services/KudaGOService.kt
> +    private val baseUrl = "https://kudago.com/public-api/v$versionApi"
Это в компаньон стоит унести, а не держать полями класса. И все пометить как `const val`.

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/services/KudaGOService.kt
> +    private val restTemplate = RestTemplate()
Вот его стоит инжектить, а еще, как обсудили в чате в телеге - стоит использовать `RestClient`.

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/services/KudaGOService.kt
> +    fun getCategories(): List<Category> {
```kotlin
fun getCategories(): List<Category> {
         logger.info("Method 'getCategories' started")
         return restTemplate.getForObject("$baseUrl/place-categories/?lang=ru", Array<Category>::class.java)
             ?.also { logger.info("Method 'getCategories' finished") }
             ?: run {
                 logger.warn("Method 'getCategories': response for place categories is null")
                 emptyList()
             }
}
```

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/utilities/Initializer.kt
> +//import annotations.LogExecutionTime
В топку!

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/utilities/Initializer.kt
> +    @LogExecutionTime
1. У тебя класс финальный по умолчанию, проксирование не работает
2. У тебя в стартере не хватает компонентов для его работы, почитай вот тут, как их стоит писать - https://habr.com/ru/articles/806217/

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/main/kotlin/com/example/homework5/utilities/Initializer.kt
> +) : ApplicationRunner {
Я бы советовал использовать `@EventListener`. Над `ApplicationRunner` мы имеем очень мало контроля (помимо примерного порядка вызовов).

2024-09-29 20:02 UTC, SHvatov commented on homework5/src/test/kotlin/com/example/homework5/Homework5ApplicationTests.kt
> +class Homework5ApplicationTests {
Тестов бы)

2024-10-01 12:53 UTC, Dimes01 commented on homework5/src/main/kotlin/com/example/homework5/services/KudaGOService.kt
> +    private val baseUrl = "https://kudago.com/public-api/v$versionApi"
logger без const, потому что "Const 'val' has type 'Logger'. Only primitives and String are allowed"

2024-10-03 09:31 UTC, Dimes01 commented on homework5/src/main/kotlin/com/example/homework5/aspects/LogExecutionTimeAspect.kt
> +        val start = System.currentTimeMillis()
Надеюсь, правильно понял)

2024-10-03 10:10 UTC, Dimes01 commented on homework5/src/test/kotlin/com/example/homework5/Homework5ApplicationTests.kt
> +class Homework5ApplicationTests {
Тесты могу из ветки `fj_2024_lesson_7` закинуть, или оставлю так и соединю всё в `main`. Сначала мердж из `fj_2024_lesson_5`, потом из `fj_2024_lesson_7` . Думаю, что такой вариант лучше будет)

2024-10-03 10:25 UTC, Dimes01 commented on homework5/build.gradle.kts
> +	implementation("org.springframework.boot:spring-boot-starter-web")
Как я понял, all-open "вшит" в плагин `kotlin("plugin.spring")`. Если я его отключаю, то выскакивает исключение:

**BeanDefinitionParsingException: Configuration problem: Configuration class 'ServiceConfiguration' may not be final. Remove the final modifier to continue.** 

На данный момент плагин для котлина оставил включенным и вроде всё работает

2024-10-14 04:46 UTC, merged